//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 WinPCK.rc 使用
//
#define IDD_MAIN                        1
#define IDI_ICON_APP                    134
#define IDI_ICON_FILE                   135
#define IDI_ICON_DIR                    136
#define IDD_DIALOG_INFO                 140
#define IDD_DIALOG_SEARCH               141
#define IDD_DIALOG_COMPRESS             142
#define IDR_MENU_MAIN                   143
#define IDS_STRING_BUTTON_FIRST         146
#define IDS_STRING_OPEN                 146
#define IDC_CURSOR_DROP                 147
#define IDS_STRING_CLOSE                147
#define IDS_STRING_INFO                 148
#define IDS_STRING_ADD                  149
#define IDS_STRING_UNPACK_SELECTED      150
#define IDI_ICON_EDIT                   150
#define IDS_STRING_UNPACK_ALL           151
#define IDI_ICON_ADD                    151
#define IDS_STRING_REBUILD              152
#define IDI_ICON_CLOSE                  152
#define IDS_STRING_SEARCH               153
#define IDI_ICON_NEW                    153
#define IDS_STRING_NEW                  154
#define IDI_ICON_OPEN                   154
#define IDS_STRING_ABOUT                155
#define IDS_STRING_BUTTON_LAST          155
#define IDI_ICON_SAVE                   155
#define IDS_STRING_COMPRESS_OPT         156
#define IDI_ICON_INFO                   156
#define IDS_STRING_CANCEL               157
#define IDI_ICON_OPT                    157
#define IDI_ICON_REBUILD                158
#define IDS_STRING_EXIT                 158
#define IDI_ICON_SAVEALL                159
#define IDS_STRING159                   159
#define IDS_STRING_DELETE               159
#define IDI_ICON_SEARCH                 160
#define IDS_STRING160                   160
#define IDS_STRING_RENAME               160
#define IDI_ICON_EXIT                   161
#define IDS_STRING161                   161
#define IDS_STRING_SELALL               161
#define IDS_STRING162                   162
#define IDS_STRING_REVSEL               162
#define IDI_ICON_STOP                   163
#define IDS_STRING_ISEXIT               163
#define IDS_STRING_ISEXITTITLE          164
#define IDS_STRING_EXITING              165
#define IDS_STRING_RENEWING             166
#define IDR_MENU_RCLICK                 167
#define IDS_STRING_RENEWOK              167
#define IDS_STRING_REBUILDING           168
#define IDS_STRING_REBUILDOK            169
#define IDD_DIALOG_VIEW                 169
#define IDS_STRING_COMPING              170
#define IDD_DIALOG_PIC                  170
#define IDS_STRING_COMPOK               171
#define IDD_DIALOG_ATTR                 171
#define IDS_STRING_EXPING               172
#define IDD_DIALOG_LOG                  172
#define IDS_STRING_EXPOK                173
#define IDS_STRING_OPENOK               174
#define IDS_STRING_OPENFAIL             175
#define IDS_STRING_OPENFILESIZE         176
#define IDS_STRING_OPENFILECOUNT        177
#define IDI_ICON_LOGE                   177
#define IDS_STRING_SEARCHING            178
#define IDI_ICON_LOGI                   178
#define IDS_STRING_SEARCHOK             179
#define IDI_ICON_LOGW                   179
#define IDS_STRING_TIMEROK              180
#define IDR_MENU_LOG                    180
#define IDS_STRING_TIMERING             181
#define IDI_ICON1                       181
#define IDI_ICON_LOGD                   181
#define IDS_STRING_LISTHEAD1            182
#define IDR_ACCELERATOR1                182
#define IDS_STRING_LISTHEAD2            183
#define IDS_STRING_LISTHEAD3            184
#define IDS_STRING_LISTHEAD4            185
#define IDD_DIALOG_REBUILD_OPT          185
#define IDS_STRING_ISDELETE             186
#define IDS_STRING_ISDELETETITLE        187
#define IDS_STRING_INVALIDFILENAME      188
#define IDS_STRING_RENAMEERROR          189
#define IDS_STRING_ERROR                190
#define IDS_STRING_PROCESS_ERROR        191
#define IDD_DIALOG_STRIP                192
#define IDC_LIST                        1010
#define IDC_PROGRESS                    1011
#define IDC_STATUS                      1012
#define IDC_TOOLBAR                     1013
#define IDC_EDIT_INFO                   1014
#define IDC_EDIT_SEARCH                 1015
#define IDC_SLIDER_LEVEL                1016
#define IDC_SLIDER_THREAD               1017
#define IDC_STATIC_LEVEL                1018
#define IDC_STATIC_THREAD               1019
#define IDC_EDIT_MEM                    1020
#define IDC_RICHEDIT_VIEW               1022
#define IDC_STATIC_PIC                  1023
#define IDC_EDIT_ATTR_NAME              1024
#define IDC_EDIT_ATTR_PATH              1025
#define IDC_EDIT_ATTR_TYPE              1026
#define IDC_EDIT_ATTR_CIPHER            1027
#define IDC_EDIT_ATTR_SIZE              1028
#define IDC_EDIT_ATTR_CMPR              1029
#define IDC_EDIT_ATTR_FILECOUNT         1030
#define IDC_EDIT_ATTR_ADDR              1031
#define IDC_EDIT_ATTR_ALLSIZE           1032
#define IDC_EDIT_ATTR_PCKSIZE           1033
#define IDC_EDIT_ATTR_PCKCMPR           1034
#define IDC_EDIT_ATTR_DIRT              1035
#define IDC_LIST_LOG                    1036
#define IDC_EDIT1                       1037
#define IDC_EDIT_VIEW                   1037
#define IDC_EDIT_SCRIPT                 1037
#define IDC_CHECK_RECPMPRESS            1038
#define IDC_BUTTON_OPEN                 1039
#define IDC_EDIT_RESULT                 1040
#define IDC_COMBO1                      1041
#define IDC_CBO_CODEPAGE                1041
#define IDC_CHECK_DDS                   1042
#define IDC_CHECK_ATT                   1043
#define IDC_CHECK3                      1044
#define IDC_CHECK_GFX                   1044
#define IDC_CHECK_GFX2                  1045
#define IDC_CHECK_ECM                   1045
#define IDC_RICHEDIT21                  1045
#define ID_MENU_COMPRESS_OPT            40000
#define ID_MENU_OPEN                    40001
#define ID_MENU_CLOSE                   40002
#define ID_MENU_INFO                    40003
#define ID_MENU_ADD                     40004
#define ID_MENU_UNPACK_SELECTED         40005
#define ID_MENU_UNPACK_ALL              40006
#define ID_MENU_REBUILD                 40007
#define ID_MENU_SEARCH                  40008
#define ID_MENU_NEW                     40009
#define ID_MENU_ABOUT                   40010
#define ID_MENU_EXIT                    40011
#define ID_MENU_RENAME                  40012
#define ID_MENU_DELETE                  40013
#define ID_MENU_SELECTALL               40014
#define ID_MENU_SELECTORP               40015
#define ID_MENU_VIEW                    40016
#define ID_40017                        40017
#define ID_MENU_ATTR                    40018
#define ID_40019                        40019
#define ID_40020                        40020
#define ID_MENU_SETUP                   40021
#define ID_MENU_UNSETUP                 40022
#define ID_40023                        40023
#define ID_MENU_LOG                     40024
#define ID_40025                        40025
#define ID_MENU_LOG_SAVE_SEL            40026
#define ID_40027                        40027
#define ID_MENU_LOG_SAVE_ALL            40028
#define ID_40029                        40029
#define ID_MENU_LOG_CLEAR               40030
#define ID_40031                        40031
#define ID_MENU_                        40032
#define ID_MENU_LOG_COPY                40033
#define ID_LISTVIEW_SELECT_ALL          40034
#define ID_LISTVIEW_BACK                40035
#define ID_CREATE_NEWPCK                40036
#define ID_OPEN_PCK                     40037
#define ID_CLOSE_PCK                    40038
#define ID_ADD_FILE_TO_PCK              40039
#define ID_LISTVIEW_SELECT_REV          40040
#define ID_LISTVIEW_ENTER               40041
#define ID_LISTVIEW_DELETE              40042
#define ID_LISTVIEW_RENAME              40044
#define ID_LISTVIEW_ATTR                40045
#define ID_LISTVIEW_POPMENU             40046
#define ID_40048                        40048
#define ID_40049                        40049
#define ID_MENU_SIM                     40050
#define ID_MENU_SIMPLIFY                40051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
